export const FIRST_INCREMENT = "FIRST_INCREMENT";
export const SET_FIRST_COUNTER = "SET_FIRST_COUNTER";
export const SECOND_INCREMENT = "SECOND_INCREMENT";
export const SET_SECOND_COUNTER = "SET_SECOND_COUNTER";
